### ISSUE TITLE
Will the pre-trained model or code be released?

### ISSUE THREAD

**Issue by wangshuo182** [yqzhishen/HarmonicNoiseSeparationGUI#1]
I can't find the onnx file. Is it not released yet? Will it be released next? Thanks.

**Comment by yqzhishen** [comment]
Sorry, the model is now released: https://github.com/yqzhishen/HarmonicNoiseSeparationGUI/releases/tag/model

Or it can be exported from https://github.com/yxlllc/vocal-remover
